#ifndef LAYERMODULE_GLOBAL_H
#define LAYERMODULE_GLOBAL_H
#include <QtCore/qglobal.h>

#if defined(LAYERMODULE_LIBRARY)
#define LAYERMODULE_EXPORT Q_DECL_EXPORT
#else
#define LAYERMODULE_EXPORT Q_DECL_IMPORT
#endif
#endif
